#!/usr/bin/env python3
"""Build a self-contained static evidence site from metadata.json.

Usage: build_site.py <run-dir>

Reads <run-dir>/metadata.json and writes:
  <run-dir>/index.html
  <run-dir>/style.css

The site opens directly via file:// — no server, no CDN, no JS framework.
Assets referenced by metadata.json (videos, screenshots) must already exist
in <run-dir>/assets/<scenario-slug>/.
"""

from __future__ import annotations

import html
import json
import sys
from pathlib import Path

STATUS_LABELS = {
    "pass": ("pass", "Pass"),
    "needs-attention": ("warn", "Needs attention"),
    "fail": ("fail", "Fail"),
}


def render(meta: dict) -> str:
    run_id = html.escape(str(meta.get("run_id", "unknown")))
    app = meta.get("app", {}) or {}
    env = meta.get("environment", {}) or {}
    scenarios = meta.get("scenarios", []) or []

    app_name = html.escape(str(app.get("name", "app")))
    app_version = html.escape(str(app.get("version", "")))
    app_target = html.escape(str(app.get("url_or_command", "")))
    env_os = html.escape(str(env.get("os", "")))
    env_browser = html.escape(str(env.get("browser", "")))

    counts = {"pass": 0, "needs-attention": 0, "fail": 0}
    for s in scenarios:
        st = s.get("status", "pass")
        if st in counts:
            counts[st] += 1

    overall_class, overall_label = "pass", "All scenarios passed"
    if counts["fail"]:
        overall_class, overall_label = "fail", f'{counts["fail"]} scenario(s) failed'
    elif counts["needs-attention"]:
        overall_class, overall_label = "warn", f'{counts["needs-attention"]} scenario(s) need attention'

    scenario_blocks = []
    for s in scenarios:
        slug = html.escape(str(s.get("slug", "scenario")))
        title = html.escape(str(s.get("title", slug)))
        narrative = html.escape(str(s.get("narrative", "")))
        notes = html.escape(str(s.get("notes", "")))
        duration = s.get("duration_seconds")
        duration_text = f"{int(duration)}s" if isinstance(duration, (int, float)) else ""
        status = s.get("status", "pass")
        status_class, status_label = STATUS_LABELS.get(status, ("pass", html.escape(status)))

        video_html = ""
        video_path = s.get("video")
        if video_path:
            v = html.escape(str(video_path))
            video_html = (
                f'<video controls preload="metadata" src="{v}">'
                f'Your browser cannot play this video. Open <a href="{v}">{v}</a> directly.'
                f"</video>"
            )

        shots_html = []
        for shot in s.get("screenshots", []) or []:
            f = html.escape(str(shot.get("file", "")))
            cap = html.escape(str(shot.get("caption", "")))
            if not f:
                continue
            shots_html.append(
                f'<figure class="shot">'
                f'<a href="{f}" target="_blank"><img src="{f}" alt="{cap}" loading="lazy"></a>'
                f'<figcaption>{cap}</figcaption>'
                f"</figure>"
            )
        shots_block = "\n".join(shots_html) if shots_html else '<p class="muted">No screenshots captured.</p>'

        notes_block = f'<p class="notes"><strong>Notes:</strong> {notes}</p>' if notes else ""
        duration_block = f'<span class="duration">{duration_text}</span>' if duration_text else ""

        scenario_blocks.append(
            f"""
<section class="scenario" id="{slug}">
  <header class="scenario-head">
    <span class="status status-{status_class}">{status_label}</span>
    <h2>{title}</h2>
    {duration_block}
  </header>
  <p class="narrative">{narrative}</p>
  {video_html}
  <div class="shots">
    {shots_block}
  </div>
  {notes_block}
</section>
"""
        )

    body_scenarios = "\n".join(scenario_blocks) if scenario_blocks else '<p class="muted">No scenarios recorded.</p>'

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>prove-it · {app_name} · {run_id}</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<header class="page-head">
  <h1>prove-it</h1>
  <p class="run-meta">
    <strong>{app_name}</strong>
    <span class="muted">{app_version}</span>
    · run <code>{run_id}</code>
  </p>
  <p class="env muted">{env_os} · {env_browser} · target <code>{app_target}</code></p>
  <p class="overall status status-{overall_class}">{overall_label}</p>
  <ul class="summary">
    <li><span class="dot dot-pass"></span> {counts['pass']} passed</li>
    <li><span class="dot dot-warn"></span> {counts['needs-attention']} need attention</li>
    <li><span class="dot dot-fail"></span> {counts['fail']} failed</li>
  </ul>
</header>
<main>
{body_scenarios}
</main>
<footer class="page-foot muted">
  Generated by the <a href="https://github.com/dvhthomas/prove-it">prove-it</a> skill.
  Open this page directly via <code>file://</code> — no server required.
</footer>
</body>
</html>
"""


CSS = """:root {
  --bg: #fafaf7;
  --fg: #1a1a1a;
  --muted: #6b6b6b;
  --line: #e3e3dd;
  --pass: #2d7a3a;
  --warn: #b86b00;
  --fail: #b3261e;
  --pass-bg: #e7f3e9;
  --warn-bg: #fcefd9;
  --fail-bg: #fbe2e0;
}
* { box-sizing: border-box; }
body {
  font: 16px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
  margin: 0;
  background: var(--bg);
  color: var(--fg);
}
code { font: 13px ui-monospace, SFMono-Regular, Menlo, monospace; background: #00000010; padding: 1px 5px; border-radius: 3px; }
.muted { color: var(--muted); }
a { color: inherit; }
.page-head {
  padding: 32px 40px 24px;
  border-bottom: 1px solid var(--line);
  background: #fff;
}
.page-head h1 { margin: 0 0 4px; font-size: 22px; letter-spacing: 0.02em; }
.run-meta { margin: 0 0 4px; }
.env { margin: 0 0 12px; font-size: 14px; }
.summary { list-style: none; margin: 8px 0 0; padding: 0; display: flex; gap: 18px; font-size: 14px; color: var(--muted); }
.dot { display: inline-block; width: 9px; height: 9px; border-radius: 50%; margin-right: 6px; vertical-align: 1px; }
.dot-pass { background: var(--pass); }
.dot-warn { background: var(--warn); }
.dot-fail { background: var(--fail); }
.status {
  display: inline-block;
  padding: 2px 10px;
  border-radius: 999px;
  font-size: 12px;
  font-weight: 600;
  letter-spacing: 0.02em;
}
.status-pass { background: var(--pass-bg); color: var(--pass); }
.status-warn { background: var(--warn-bg); color: var(--warn); }
.status-fail { background: var(--fail-bg); color: var(--fail); }
.overall { display: inline-block; margin: 12px 0 0; }
main { padding: 24px 40px 60px; max-width: 1100px; }
.scenario {
  margin: 28px 0;
  padding: 20px 24px;
  background: #fff;
  border: 1px solid var(--line);
  border-radius: 8px;
}
.scenario-head { display: flex; align-items: baseline; gap: 12px; flex-wrap: wrap; }
.scenario-head h2 { margin: 0; font-size: 18px; }
.duration { color: var(--muted); font-size: 13px; }
.narrative { margin: 8px 0 16px; color: #2a2a2a; }
.scenario video {
  width: 100%;
  max-width: 1024px;
  border-radius: 6px;
  background: #000;
  display: block;
  margin: 0 0 16px;
}
.shots {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
  gap: 12px;
  margin: 0 0 12px;
}
.shot { margin: 0; }
.shot img {
  width: 100%;
  height: auto;
  display: block;
  border-radius: 4px;
  border: 1px solid var(--line);
  background: #fff;
}
.shot figcaption { font-size: 12px; color: var(--muted); margin-top: 4px; }
.notes { background: #fff8e1; border-left: 3px solid var(--warn); padding: 8px 12px; margin: 12px 0 0; font-size: 14px; }
.page-foot { padding: 16px 40px 40px; font-size: 13px; }
"""


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: build_site.py <run-dir>", file=sys.stderr)
        return 2

    run_dir = Path(sys.argv[1]).expanduser().resolve()
    meta_path = run_dir / "metadata.json"

    if not meta_path.exists():
        print(f"missing: {meta_path}", file=sys.stderr)
        return 1

    meta = json.loads(meta_path.read_text())
    (run_dir / "index.html").write_text(render(meta))
    (run_dir / "style.css").write_text(CSS)
    print(f"wrote: {run_dir / 'index.html'}")
    print(f"wrote: {run_dir / 'style.css'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
